<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SpecialisationSubcategory;

class SpecialisationSubcategorySeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'category_id' => 2,
                'title' => 'Cath Lab MEP Works',
                'slug' => 'cath-lab-mep-works',
                'banner_tags' => array (
  0 => 'Radiation-Shielded',
  1 => 'Isolated Power',
),
                'banner_image' => 'assets/img/specialisation/cath_lab_hero.webp',
                'image' => 'assets/img/specialisation/cath_lab_hero.webp',
                'description' => 'Cath lab MEP — radiation-shielded service penetrations, dedicated UPS, isolated IT system, precision chilled water cooling for imaging, medical gas, radiation-safe cable routing through shielded walls.',
                'cta_title' => 'Need specialist MEP for your hospital area?',
                'cta_description' => 'Tell us the clinical area and we\'ll outline our approach and timeline.',
                'cta_button_url' => 'contact',
                'features_heading' => array (
  0 => 'Shielding',
  1 => 'Power',
  2 => 'Cooling',
  3 => 'MGPS',
),
                'features_description' => array (
  0 => 'Radiation-shielded MEP penetrations coordinated with physicist',
  1 => 'Isolated IT system, UPS, dedicated circuits for imaging',
  2 => 'Precision chilled water for C-arm and imaging heat rejection',
  3 => 'O₂, vacuum and medical air at procedural position',
),
                'tags' => array (
  0 => 'Cath Lab MEP',
  1 => 'Radiation Shield',
  2 => 'Isolated Power',
  3 => 'Precision Cooling',
),
                'seo_text' => 'cath lab MEP works · cath lab HVAC contractor · cath lab electrical systems',
                'status' => true,
            ],
            [
                'category_id' => 2,
                'title' => 'Clean Room MEP',
                'slug' => 'clean-room-mep',
                'banner_tags' => array (
  0 => 'ISO 14644',
  1 => 'HEPA H14',
  2 => 'Pressure Cascades',
),
                'banner_image' => 'assets/img/specialisation/clean_room_hero.webp',
                'image' => 'assets/img/specialisation/clean_room_hero.webp',
                'description' => 'Clean room MEP — ISO 14644 Class 5 to 8 environments, HEPA/ULPA air handling, pressure differential control, flush wall/ceiling light integration, ESD flooring and validation testing (DOP, particle counts).',
                'cta_title' => 'Need specialist MEP for your hospital area?',
                'cta_description' => 'Tell us the clinical area and we\'ll outline our approach and timeline.',
                'cta_button_url' => 'contact',
                'features_heading' => array (
  0 => 'Class',
  1 => 'Air Handling',
  2 => 'Controls',
  3 => 'Validation',
),
                'features_description' => array (
  0 => 'ISO Class 5 to Class 8 validated cleanrooms',
  1 => 'HEPA H14 / ULPA terminal filter modules with terminal dampers',
  2 => 'Differential pressure indicators and automated air balancing',
  3 => 'DOP testing, particle counts and air velocity profiling',
),
                'tags' => array (
  0 => 'Clean Room MEP',
  1 => 'ISO 14644',
  2 => 'HEPA H14',
  3 => 'Particle Counts',
),
                'seo_text' => '',
                'status' => true,
            ],
            [
                'category_id' => 2,
                'title' => 'CSSD & Sterile Services',
                'slug' => 'cssd-sterile-services',
                'banner_tags' => array (
  0 => 'Sterile Zoning',
  1 => 'RO Steam Supply',
  2 => 'HTM 2010',
),
                'banner_image' => 'assets/img/specialisation/cssd_hero.webp',
                'image' => 'assets/img/specialisation/cssd_hero.webp',
                'description' => 'CSSD MEP — three-zone pressure cascade (soiled, clean, sterile), pure steam generator supply, RO/DI water plant integration, high-temp drainage, autoclave steam exhaust and washer-disinfector utility hooks.',
                'cta_title' => 'Need specialist MEP for your hospital area?',
                'cta_description' => 'Tell us the clinical area and we\'ll outline our approach and timeline.',
                'cta_button_url' => 'contact',
                'features_heading' => array (
  0 => 'Zoning',
  1 => 'Water/Steam',
  2 => 'Exhaust',
  3 => 'Standards',
),
                'features_description' => array (
  0 => 'Strict 3-zone pressure cascade to prevent cross-contamination',
  1 => 'RO water plant & pure steam generator piping for autoclaves',
  2 => 'Dedicated high-temp moisture exhaust for sterilizers',
  3 => 'Compliant with HTM 2010, HTM 2031 & NABH CSSD guidelines',
),
                'tags' => array (
  0 => 'CSSD MEP',
  1 => 'Pure Steam',
  2 => 'RO Water',
  3 => 'Sterile Zoning',
),
                'seo_text' => '',
                'status' => true,
            ],
            [
                'category_id' => 2,
                'title' => 'Diagnostic Centre MEP',
                'slug' => 'diagnostic-centre-mep',
                'banner_tags' => array (
  0 => 'MRI RF Cage',
  1 => 'Lead Shielding',
  2 => 'Chilled Water',
),
                'banner_image' => 'assets/img/specialisation/diagnostic_hero.webp',
                'image' => 'assets/img/specialisation/diagnostic_hero.webp',
                'description' => 'Diagnostic Centre MEP — MRI RF shield penetrations & helium quench pipe exhaust, CT scanner precision cooling chillers, X-ray/Mammography lead lining coordination, PET-CT hot lab ventilation, high-KVA power stabilization.',
                'cta_title' => 'Need specialist MEP for your hospital area?',
                'cta_description' => 'Tell us the clinical area and we\'ll outline our approach and timeline.',
                'cta_button_url' => 'contact',
                'features_heading' => array (
  0 => 'MRI MEP',
  1 => 'CT & X-Ray',
  2 => 'PET-CT',
  3 => 'Power Quality',
),
                'features_description' => array (
  0 => 'RF enclosure penetration filters & quench pipe safety relief duct',
  1 => 'Precision water chillers & lead-lined electrical outlet backings',
  2 => 'Radioisotope hot lab negative pressure exhaust to AERB norms',
  3 => 'Harmonic filters & dedicated isolation transformers for imaging',
),
                'tags' => array (
  0 => 'Diagnostic MEP',
  1 => 'MRI RF Cage',
  2 => 'CT Chiller',
  3 => 'AERB Norms',
),
                'seo_text' => '',
                'status' => true,
            ],
            [
                'category_id' => 2,
                'title' => 'ICU, NICU & CCU MEP',
                'slug' => 'icu-nicu-ccu-mep',
                'banner_tags' => array (
  0 => 'Isolation Rooms',
  1 => 'Dual Gas Pendants',
  2 => '100% UPS',
),
                'banner_image' => 'assets/img/specialisation/icu_mep_hero.webp',
                'image' => 'assets/img/specialisation/icu_mep_hero.webp',
                'description' => 'ICU, NICU & CCU MEP — positive/negative pressure isolation rooms with anterooms, dual-source MGPS bedhead columns, 100% UPS backup with zero break time, low-noise HVAC, nurse call integration.',
                'cta_title' => 'Need specialist MEP for your hospital area?',
                'cta_description' => 'Tell us the clinical area and we\'ll outline our approach and timeline.',
                'cta_button_url' => 'contact',
                'features_heading' => array (
  0 => 'Isolation',
  1 => 'MGPS',
  2 => 'Power',
  3 => 'HVAC',
),
                'features_description' => array (
  0 => 'Negative pressure isolation rooms for airborne infection control',
  1 => 'Dual O₂, Vacuum & Medical Air connections per bed position',
  2 => 'Class 1 & Class 2 isolated electrical supply with 100% UPS',
  3 => 'Low-decibel laminar & filtered air supply for infant/critical care',
),
                'tags' => array (
  0 => 'ICU MEP',
  1 => 'NICU Infrastructure',
  2 => 'Isolation Rooms',
  3 => 'Zero Break UPS',
),
                'seo_text' => '',
                'status' => true,
            ],
            [
                'category_id' => 2,
                'title' => 'Modular & Prefabricated OT',
                'slug' => 'modular-prefabricated-ot',
                'banner_tags' => array (
  0 => 'Prefab Panels',
  1 => 'Flush Services',
  2 => 'Modular Design',
),
                'banner_image' => 'assets/img/specialisation/modular_ot_hero.webp',
                'image' => 'assets/img/specialisation/modular_ot_hero.webp',
                'description' => 'Modular & Prefabricated OT MEP — pre-engineered wall panel integrations, stainless steel / HPL cladding, hermetically sealing sliding doors, ceiling pendant support structures, touch-screen surgeon control panels.',
                'cta_title' => 'Need specialist MEP for your hospital area?',
                'cta_description' => 'Tell us the clinical area and we\'ll outline our approach and timeline.',
                'cta_button_url' => 'contact',
                'features_heading' => array (
  0 => 'Cladding',
  1 => 'Control Panel',
  2 => 'Pendants',
  3 => 'Doors',
),
                'features_description' => array (
  0 => 'Antibacterial SS/HPL wall panels with flush MEP cutouts',
  1 => 'Integrated surgeon control panel for gas, HVAC & lighting',
  2 => 'Ceiling structural grid for heavy surgical & anesthesia pendants',
  3 => 'Hermetically sealing automated sliding doors with air locks',
),
                'tags' => array (
  0 => 'Modular OT',
  1 => 'HPL Wall Panels',
  2 => 'Surgeon Control Panel',
  3 => 'Hermetic Doors',
),
                'seo_text' => '',
                'status' => true,
            ],
            [
                'category_id' => 2,
                'title' => 'NABH Compliance MEP',
                'slug' => 'nabh-compliance-mep',
                'banner_tags' => array (
  0 => 'Audit Ready',
  1 => '100% NABH',
  2 => 'Validation Docs',
),
                'banner_image' => 'assets/img/specialisation/nabh_compliance_hero.webp',
                'image' => 'assets/img/specialisation/nabh_compliance_hero.webp',
                'description' => 'NABH Compliance MEP — Turnkey engineering designed to pass NABH and NABL audits on the first attempt. Full documentation, air balance certificates, lux level mapping, pressure differential logs, MGPS purity tests.',
                'cta_title' => 'Need specialist MEP for your hospital area?',
                'cta_description' => 'Tell us the clinical area and we\'ll outline our approach and timeline.',
                'cta_button_url' => 'contact',
                'features_heading' => array (
  0 => 'Air Quality',
  1 => 'MGPS Purity',
  2 => 'Fire Safety',
  3 => 'Documentation',
),
                'features_description' => array (
  0 => 'ACH, positive pressure & HEPA H14 validation per NABH guidelines',
  1 => 'HTM 02-01 gas purity, dewpoint & pressure stability certification',
  2 => 'NBC Part 4 life safety, smoke dampers & fire NOC support',
  3 => 'Complete commissioning dossier & AS-BUILT BIM drawings for audit',
),
                'tags' => array (
  0 => 'NABH MEP',
  1 => 'Audit Ready',
  2 => 'Air Balance Certs',
  3 => 'Fire NOC Support',
),
                'seo_text' => '',
                'status' => true,
            ],
            [
                'category_id' => 2,
                'title' => 'Operation Theatre (OT) MEP',
                'slug' => 'operation-theatre-ot-mep',
                'banner_tags' => array (
  0 => 'Modular OT',
  1 => 'Laminar Airflow',
  2 => 'NABH',
),
                'banner_image' => 'assets/img/specialisation/ot_mep_hero.webp',
                'image' => 'assets/img/specialisation/ot_mep_hero.webp',
                'description' => 'Full MEP for modular and conventional OTs — laminar airflow HVAC, positive pressure cascade, HEPA H14, isolated IT system, surgical pendants, medical gas at operating position. Validated commissioning to NABH and ASHRAE 170.',
                'cta_title' => 'Need specialist MEP for your hospital area?',
                'cta_description' => 'Tell us the clinical area and we\'ll outline our approach and timeline.',
                'cta_button_url' => 'contact',
                'features_heading' => array (
  0 => 'HVAC',
  1 => 'Power',
  2 => 'MGPS',
  3 => 'Validation',
),
                'features_description' => array (
  0 => 'Laminar airflow, +2.5 Pa above corridor, 20 ACH, HEPA H14',
  1 => 'IT isolated system, UPS-backed, 1,000 lux OT task lighting',
  2 => 'O₂, vacuum, N₂O, medical air at operating position',
  3 => 'Particle count, pressure test, air balance certificates',
),
                'tags' => array (
  0 => 'Laminar Airflow',
  1 => 'HEPA H14',
  2 => 'IT System',
  3 => 'OT Pendants',
  4 => 'Modular OT',
  5 => 'NABH',
),
                'seo_text' => 'OT MEP contractor · OT HVAC design and execution · modular OT MEP contractor · operation theatre HVAC contractor',
                'status' => true,
            ],
        ];

        foreach ($data as $item) {
            SpecialisationSubcategory::updateOrCreate(['slug' => $item['slug']], $item);
        }
    }
}
